version: '3'

services:
  snipeit:
    image: sc3p73r/snipeit:v1.0.1
    container_name: snipe
    ports:
      - "8000:80"
    volumes:
      - ./storage/logs:/var/www/html/storage/logs
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - snipeit-backend

  mariadb:
    image: sc3p73r/snipe-mysql:v1.0.1
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - snipeit-backend
    ports:
      - "3306:3306"

volumes:
  db: {}

networks:
  snipeit-backend:



